### ISSUE TITLE
Can't add my Raumfeld Stereo Cubes

### ISSUE THREAD

**Issue by albi** [RandomMetalhead/homebridge-teufel#12]
Hi,

thanks for the great plugin which was working most of the time for me. But after reinstalling my Raspi 4, my Stereo Cubes from Teufel (former Raumfeld) won't be added. I've tried different settings like:

```
{
    "platform": "Teufel",
    "name": "Teufel"
}

{
    "platform": "Teufel",
    "name": "Raumfeld"
}

{
    "platform": "Teufel",
    "name": "stereo-cubes"
}
```

"stereo-cubes" is the network name of them.

None of these settings will work. Kind of clueless now what to do.

**Comment by RandomMetalhead** [comment]
Hi,

Sorry for the late answer. Do you have the logs from homebridge startup?

Greetings,
Marcus

**Comment by albi** [comment]
No problem, it was christmas ;)

My startup log…

```
[2019-12-30 8:43:19] Loaded config.json with 2 accessories and 4 platforms.
[2019-12-30 8:43:19] ---
[2019-12-30 8:43:19] Loaded plugin: homebridge-config-ui-x
[2019-12-30 8:43:19] Registering platform 'homebridge-config-ui-x.config'
[2019-12-30 8:43:19] ---
[2019-12-30 8:43:19] Loaded plugin: homebridge-panasonic-viera-tv
[2019-12-30 8:43:19] Registering accessory 'homebridge-panasonic.Panasonic-TV'
[2019-12-30 8:43:19] ---
[2019-12-30 8:43:19] Loaded plugin: homebridge-people-x
[2019-12-30 8:43:21] Registering platform 'homebridge-people.PeopleX'
[2019-12-30 8:43:21] Registering accessory 'homebridge-people.PeopleAccessory'
[2019-12-30 8:43:21] Registering accessory 'homebridge-people.PeopleAllAccessory'
[2019-12-30 8:43:21] ---
[2019-12-30 8:43:21] Loaded plugin: homebridge-pushed-notification
[2019-12-30 8:43:21] Registering accessory 'homebridge-pushed-notifications.GetPushedNotification'
[2019-12-30 8:43:21] ---
[2019-12-30 8:43:22] Loaded plugin: homebridge-teufel
[2019-12-30 8:43:22] Registering platform 'homebridge-teufel.Teufel'
[2019-12-30 8:43:22] ---
[2019-12-30 8:43:23] Loaded plugin: homebridge-yamaha-home
[2019-12-30 8:43:23] Registering platform 'homebridge-yamaha-home.yamaha-home'
[2019-12-30 8:43:23] ---
[2019-12-30 8:43:23] Loading 4 platforms...
[2019-12-30 8:43:23] [Config] Initializing config platform...
[2019-12-30 8:43:23] [Config] Spawning homebridge-config-ui-x with PID 29695
[2019-12-30 8:43:23] [PeopleX] Initializing PeopleX platform...
[2019-12-30 8:43:23] [PeopleX] Initializing platform accessory 'Albi'...
[2019-12-30 8:43:23] [PeopleX] Initializing platform accessory 'Grit'...
[2019-12-30 8:43:23] [PeopleX] Initializing platform accessory 'Anyone'...
[2019-12-30 8:43:23] [PeopleX] Initializing platform accessory 'No One'...
[2019-12-30 8:43:23] [PeopleX] WebHook: Started server on port '51828'.
[2019-12-30 8:43:23] [yamaha-home] Initializing yamaha-home platform...
[2019-12-30 8:43:23] [yamaha-home] Getting Yamaha AVR devices.
[2019-12-30 8:43:23] [yamaha-home] Possible Yamaha device discovered Yamaha undefined
[2019-12-30 8:43:23] [Raumfeld] Initializing Teufel platform...
[2019-12-30 8:43:23] Loading 2 accessories...
[2019-12-30 8:43:23] [Fernseher] Initializing Panasonic-TV accessory...
[2019-12-30 8:43:23] [Fernseher] Adding Input 1: Name: TV, Type: TV
[2019-12-30 8:43:23] [Fernseher] Adding Input 2: Name: Plex, Type: APPLICATION
[2019-12-30 8:43:23] [Fernseher] Adding Input 3: Name: YouTube, Type: APPLICATION
[2019-12-30 8:43:23] [Fernseher] Adding Input 4: Name: Aufnahmen, Type: APPLICATION
[2019-12-30 8:43:23] [Fernseher] Initialization complete.
[2019-12-30 8:43:23] [Pushed.co] Initializing GetPushedNotification accessory...
[2019-12-30 8:43:23] [Pushed.co]  app key DMBFuxFwsE0llVTSDe3C
[2019-12-30 8:43:23] [Pushed.co]  event Albi Homebridge
[2019-12-30 8:43:23] [Pushed.co]  message undefined
[2019-12-30 8:43:23] [Pushed.co]  mute notification interval in sec 60
[2019-12-30 8:43:23] [yamaha-home] Found Yamaha WXC-50 - 05525EF3, "Yamaha"
[2019-12-30 8:43:23] [yamaha-home] Making accessory "▶ TV" for input 1
[2019-12-30 8:43:23] [yamaha-home] Adding Input Switch ▶ TV
[2019-12-30 8:43:23] [yamaha-home] Making accessory "▶ AirPlay" for input 2
[2019-12-30 8:43:23] [yamaha-home] Adding Input Switch ▶ AirPlay
[2019-12-30 8:43:23] [yamaha-home] Adding zone controller for Main
[2019-12-30 8:43:23] [yamaha-home] Possible Yamaha device discovered Wohnzimmer [ '10.0.1.8' ]
[2019-12-30 8:43:24] [yamaha-home] WARN: Got multiple systems with ID 05525EF3! Omitting duplicate!
[2019-12-30 8:43:24] [yamaha-home] Possible Yamaha device discovered RaumfeldControl on Raumfeld Stereo Cubes [ '10.0.1.21' ]
[2019-12-30 8:43:24] [yamaha-home] Possible Yamaha device discovered Bad [ '10.0.1.9', 'fe80::4e1b:86ff:fe64:e94e' ]
Unhandled rejection ReferenceError: timeoutFunction is not defined
    at YamahaAVRPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha-home/index.js:272:9)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:489:14)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:704:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:730:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-home/node_modules/bluebird/js/release/promise.js:604:18)
[2019-12-30 8:43:27] [Config] Homebridge Config UI X v4.6.7 is listening on :: port 8080
[2019-12-30 8:43:28] [yamaha-home] Discovery finished, found 3 Yamaha AVR devices.
[2019-12-30 8:43:28] [yamaha-home] Initializing platform accessory '▶ TV'...
[2019-12-30 8:43:28] [yamaha-home] Initializing platform accessory '▶ AirPlay'...
[2019-12-30 8:43:28] [yamaha-home] Initializing platform accessory 'Main'...
Setup Payload:
X-HM://0023ISYWY9FFE
```

**Comment by RandomMetalhead** [comment]
I can not see any Raumfeld device in the logs. Do you have any other Raumfeld device, which is currently working?

Also I found this log entry from yamaha-home very odd

`[2019-12-30 8:43:24] [yamaha-home] Possible Yamaha device discovered RaumfeldControl on Raumfeld Stereo Cubes [ '10.0.1.21' ]`

**Comment by albi** [comment]
Got the yamaha-home plugin running for adding my Yamaha Receiver. Yes the device at 10.0.1.21 are the Raumfeld Stereo Cubes.

**Comment by RandomMetalhead** [comment]
Can you try uninstalling the "yamaha-home" plugin and restart, just for testing? I am curious, if the yamaha-home plugin has something to do with it, that my plugin can not find the cubes...

**Comment by albi** [comment]
yeah. but next year ;) too much trouble now.

**Comment by RandomMetalhead** [comment]
Closing, because not feedback

**Comment by albi** [comment]
Sorry, for not giving feedback. I've deinstalled Yamaha-Home but my Stereo Cubes won't be found. Which one is the correct syntax?

`{
    "platform": "Teufel",
    "name": "Teufel"
}

{
    "platform": "Teufel",
    "name": "Raumfeld"
}

{
    "platform": "Teufel",
    "name": "stereo-cubes"
}`

**Comment by RandomMetalhead** [comment]
Hi Albi,
you only need one plattform. The name of the plattform is not important. Important is, that you only define one plattform!

Check this:
https://github.com/RandomMetalhead/homebridge-teufel/blob/master/config-sample.json

The plattform itself will add all speakers you have, if they are avaiblable in a zone.

**Comment by albi** [comment]
For sure there was only one of the three definitions in my config. The name is not important? Good to know! But still no Stereo Cubes visible here. I've once had them running with another plugin. So they are visible/available in my network.

**Comment by RandomMetalhead** [comment]
Hey Albi, please check new version 0.4.7. It may also solve your problem

**Comment by albi** [comment]
Works! Got my Raumfeld Stereo Cubes in HomeKit now!
