### ISSUE TITLE
TypeError: Winston.transports.DailyRotateFile is not a constructor

### ISSUE THREAD

**Issue by philippgerard** [RandomMetalhead/homebridge-teufel#13]
Homebridge: 0.4.50 (via HOOBS 3.1.22)
Node: 12.13.1
homebridge-teufel: 0.4.4

Error:
`[Homebridge] [3/4/2020, 19:37:03] TypeError: Winston.transports.DailyRotateFile is not a constructor
    at Logger.initExternalLogger (/home/hoobs/.hoobs/node_modules/node-raumkernel/lib/lib.logger.js:64:21)
    at new Logger (/home/hoobs/.hoobs/node_modules/node-raumkernel/lib/lib.logger.js:28:14)
    at Raumkernel.createLogger (/home/hoobs/.hoobs/node_modules/node-raumkernel/lib/lib.raumkernel.js:49:25)
    at new TeufelPlatform (/home/hoobs/.hoobs/node_modules/homebridge-teufel/index.js:34:21)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:293:34)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11`

**Comment by RandomMetalhead** [comment]
This seems to be a problem in raumserver itself. You need to open an issue there:
https://github.com/ChriD/node-raumserver
