### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ulilicht** [RandomMetalhead/homebridge-teufel#16]
Hi there,

first of all, thanks for creating this plugin! 

I installed in on homebridge but only get the following error. I use the default config from example. Any hint what could be the root cause? 

My setup: 
Raumfeld system with 3 rooms, all second Generation Raumfeld 
Node v14.16.1

I use `node-raumkernel` in the same network together with [Raumbar](https://github.com/ulilicht/Raumbar), there it works without issues. 

Thanks! 
Uli

```
[14/04/2021, 23:13:57] [Config] Initializing config platform...
[14/04/2021, 23:13:57] [Config] Running in Service Mode
[14/04/2021, 23:13:58] [Hue] Initializing Hue platform...
[14/04/2021, 23:13:58] [Hue] homebridge-hue v0.13.5, node v14.16.1, homebridge v1.3.4
[14/04/2021, 23:13:58] [Hue] warning: recommended version: node v14.16.0 LTS
[14/04/2021, 23:13:58] [Hue] config.json: nupnp: invalid key
[14/04/2021, 23:13:59] [Teufel] Initializing Teufel platform...
[14/04/2021, 23:14:05] [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1943185030, api v1.43.0
[14/04/2021, 23:14:10] TypeError: Cannot read property '0' of undefined
    at TeufelPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-teufel/index.js:65:51)
    at Raumkernel.<anonymous> (/usr/local/lib/node_modules/homebridge-teufel/index.js:55:25)
    at Raumkernel.emit (events.js:315:20)
    at Raumkernel.setSystemReady (/usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.raumkernel.js:125:18)
    at Raumkernel.onMediaServerRaumfeldAdded (/usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.raumkernel.js:189:14)
    at DeviceManager.<anonymous> (/usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.raumkernel.js:92:124)
    at DeviceManager.emit (events.js:315:20)
    at DeviceManager.createMediaServerRaumfeld (/usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.manager.deviceManager.js:561:14)
    at /usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.manager.deviceManager.js:408:34
    at /usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.external.upnp-device-client.js:48:5
    at /usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.external.upnp-device-client.js:670:7
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/homebridge-teufel/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:327:22)
    at finishMaybe (/usr/local/lib/node_modules/homebridge-teufel/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (/usr/local/lib/node_modules/homebridge-teufel/node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
error: uncaughtException: Cannot read property '0' of undefined date=Wed Apr 14 2021 23:14:10 GMT+0200 (Central European Summer Time), pid=14200, uid=1000, gid=1000, cwd=/var/lib/homebridge, execPath=/usr/local/bin/node, version=v14.16.1, argv=[/usr/local/bin/node, /usr/local/lib/node_modules/homebridge/bin/homebridge, -C, -Q, -U, /var/lib/homebridge, -I], rss=77283328, heapTotal=38191104, heapUsed=35142300, external=2103971, arrayBuffers=329278, loadavg=[2.33, 2.12, 1.65], uptime=3932531
TypeError: Cannot read property '0' of undefined
    at TeufelPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-teufel/index.js:65:51)
    at Raumkernel.<anonymous> (/usr/local/lib/node_modules/homebridge-teufel/index.js:55:25)
    at Raumkernel.emit (events.js:315:20)
    at Raumkernel.setSystemReady (/usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.raumkernel.js:125:18)
    at Raumkernel.onMediaServerRaumfeldAdded (/usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.raumkernel.js:189:14)
    at DeviceManager.<anonymous> (/usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.raumkernel.js:92:124)
    at DeviceManager.emit (events.js:315:20)
    at DeviceManager.createMediaServerRaumfeld (/usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.manager.deviceManager.js:561:14)
    at /usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.manager.deviceManager.js:408:34
    at /usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.external.upnp-device-client.js:48:5
    at /usr/local/lib/node_modules/homebridge-teufel/node_modules/node-raumkernel/lib/lib.external.upnp-device-client.js:670:7
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/homebridge-teufel/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:327:22)
    at finishMaybe (/usr/local/lib/node_modules/homebridge-teufel/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (/usr/local/lib/node_modules/homebridge-teufel/node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[14/04/2021, 23:14:14] Got SIGTERM, shutting down Homebridge...
```

**Comment by iamsebastian** [comment]
Hej @ulilicht,

Maybe not interesting anymore, but as this issue is still uncommented ...

Got the same issues, until my room wasn't unassigned anymore. Did the config with `pyfeld`.

Logs looked like this:

```bash
❯ pyfeld --discover info
Mediaserver #0
Zone #0 : unassigned room
	Room 'Wohnzimmer'
		Renderer 'Speaker Wohnzimmer'

❯ pyfeld unassignedrooms     
Wohnzimmer

❯ pyfeld zones                

❯ pyfeld createzone Wohnzimmer
zone creation adding rooms:
uuid:45f5969a-54f8-4c2c-8251-xxxxxxxxxxxx

❯ pyfeld zones                
Wohnzimmer

❯ pyfeld addtozone Wohnzimmer 
http://192.168..../connectRoomsToZone?zoneUDN=uuid:45ad9e40-9689-45a1-b46a-xxxxxxxxxxxx&roomUDNs=uuid:45f5969a-54f8-4c2c-8251-xxxxxxxxxxxx
zone creation adding rooms:
uuid:45f5969a-54f8-4c2c-8251-xxxxxxxxxxxx

❯ pyfeld --discover info      
Mediaserver #0
Zone #0 : Wohnzimmer
	Room 'Wohnzimmer'
		Renderer 'Speaker Wohnzimmer'
```
